project:
  type: book
  output-dir: docs

book:
  title: "Portfolio"
  author: "Erik King-Vargas"
  date: 10/2/2023
  search: true
  page-navigation: true
  repo-url: https://github.com/erikvvargas/portfolio
  sidebar:
    tools:
      # - icon: share-fill
      #   href: https://erik-king-vargas.carrd.co/
      - icon: linkedin
        href: https://www.linkedin.com/in/erikvvargas/
      - icon: envelope
        href: mailto:erikvvargas@gmail.com
  chapters:
    - index.qmd
    - spotify_data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    number-sections: false
  pdf:
    documentclass: scrreprt